DROP TABLE ROLE_TYPE;
DROP TABLE SAT_USER;
/
--Lookup table 1-Employee, 2-Manager
CREATE TABLE ROLE_TYPE
  (
    RT_ID   INT,
    RT_NAME VARCHAR2(4000) UNIQUE,
    PRIMARY KEY(RT_ID)
  );
/
CREATE TABLE _USER
  (
    _ID       INT,
    FN       VARCHAR2(4000),
    LS       VARCHAR2(4000),
    USERNAME VARCHAR2(4000) UNIQUE NOT NULL,
    PASSWORD VARCHAR2(4000) NOT NULL,
    RT_ID        INT DEFAULT 1 NOT NULL,
    EMAIL    VARCHAR2(4000),
    PRIMARY KEY(_ID),
    FOREIGN KEY(RT_ID) REFERENCES ROLE_TYPE(RT_ID)
  );
/
--Lookup table
CREATE TABLE CARD
  (
    C_ID INT,
    L_ID INT,
    C_WORTH INT,
    C_NAME VARCHAR2(4000) UNIQUE,
    C_LANE VARCHAR2(4000) NOT NULL,
    C_DESCRIPTION VARCHAR2(4000),
    PRIMARY KEY(_ID)
  );
/
--Lookup table 1-Pending, 2-Approved, 3-Denied
CREATE TABLE TASK
  (
    T_ID   INT,
    C_ID INT,
    T_INFO VARCHAR2(4000) UNIQUE,
    PRIMARY KEY(T_ID),
    FOREIGN KEY(C_ID) REFERENCES CARD(C_ID)
  );
/
CREATE TABLE LANE
  (
    L_ID INT,
    _ID INT,
    L_NAME ARCHAR2(4000) UNIQUE,
  PRIMARY KEY(L_ID)
  );
/

COMMIT;