INSERT INTO ROLE_TYPE(RT_NAME) VALUES('EMPLOYEE'); 
INSERT INTO ROLE_TYPE(RT_NAME) VALUES('MANAGER'); 
/
INSERT INTO TV2_USER (TV2_FN,
TV2_LS,
TV2_USERNAME,
TV2_PASSWORD,
RT_ID,
TV2_EMAIL) VALUES('john','last','j','j',1,'tenoriom54@yahoo.com');
/
INSERT INTO BOARD(TV2_ID,B_TITLE) VALUES (1,'JOHN');
INSERT INTO LANE(B_ID,L_TITLE) VALUES (1,'JOHNS IS GOOD');
INSERT INTO CARD(L_ID,C_VERIFY,C_WORTH,C_TITLE,C_DESCRIPTION) VALUES (1,0,8,'STORY','USER CARD');
INSERT INTO TASK(C_ID,T_COMPLETE,T_INFO) VALUES (1,0,'DO OUR DATABASE');
/
ALTER TABLE BOARD ADD TOTAL INT;
/
ALTER TABLE TV2_USER ADD TEAM INT DEFAULT 0;
/
ALTER TABLE TV2_USER  RENAME COLUMN TEAM TO TV2_TEAM;
/
ALTER TABLE BOARD ADD TEAM INT DEFAULT 0;
/
COMMIT;